### ISSUE TITLE
Support Need for ppc64le arch

### ISSUE THREAD

**Issue by gauravpbankar** [latchset/tang-operator#10]
- As part of the security worker on OCP Compliance Operator we do need to get Tang Operator working on Power for volume encryption task.  

- So we are trying to install operator on ppc64le and currently we dont have support for ppc64le so we are trying to build images for power using source code change. 

- There is change in Docker file related to arch we have added and build images for operator, bundle and catalogs etc.

- Now trying to deploy tang operator using bundle images,:
- Getting error for  operator-sdk run command:
```
operator-sdk run bundle quay.io/gauravbankar/tang-operator-bundle:v0.0.24
INFO[0008] Successfully created registry pod: quay-io-gauravbankar-tang-operator-bundle-v0-0-24
INFO[0008] Created CatalogSource: tang-operator-catalog
INFO[0008] Created Subscription: tang-operator-v0-0-24-sub
FATA[0120] Failed to run bundle: install plan is not available for the subscription tang-operator-v0-0-24-sub: timed out waiting for the condition```

Description for subscription:

   Message:               constraints not satisfiable: @existing/default//tang-operator.v0.0.24 and tang-operator-catalog/default/alpha/tang-operator.v0.0.24 originate from package tang-operator, subscription tang-operator-v0-0-24-sub requires tang-operator-catalog/default/alpha/tang-operator.v0.0.24, subscription tang-operator-v0-0-24-sub exists, clusterserviceversion tang-operator.v0.0.24 exists and is not referenced by a subscription
    Reason:                ConstraintsNotSatisfiable
```

can you please help to get resolve this issue?

**Comment by sarroutbi** [comment]
As tang-operator was integrated in OCP, if you wish to generate an alternative for it you might generate it with different name, to avoid collision with the one existing in OCP.

Can you please share your modifications to try to reproduce it?

**Comment by gauravpbankar** [comment]
Hi @sarroutbi ,

I have updated change related to architect in Dockerfile which can be use for the operator image.


-RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go
+RUN CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le go build -a -o manager main.go

and as per description it is not related to naming of operator it is more looking like issure related to install plan which is not available for particular subscription.

can you please look into it?

**Comment by gauravpbankar** [comment]
Hi @sarroutbi ,

Tang operator is working fine after i have followed your blogpost :
https://cloud.redhat.com/blog/tang-operator-providing-nbde-in-openshift#:~:text=You%20can%20deploy%20a%20tang,provides%20to%20achieve%20this%20automation.

But only seems the preblem for the clevis steps i am not able to make up clevis machine after rebooting.

**Comment by gauravpbankar** [comment]
i have tried above command to test whether tang operator is working : 

i can see below result:

``` #echo "top secret" | clevis encrypt tang '{"url":"http://URL"}' > test.jwe
The advertisement contains the following signing keys:

aGBhcy1jOPH_utAclZKzfmF65IM

Do you wish to trust these keys? [ynYN] y
# clevis decrypt tang '{"url":"<<URL>>"}' < test.jwe
top secret
```

is it fine?

**Comment by sarroutbi** [comment]
Yes, that is fine. It seems correctly configured.
