### ISSUE TITLE
TangOperator Install fails on S390x.

### ISSUE THREAD

**Issue by mp-redhat** [latchset/tang-operator#14]
While installing tang operator in s390x  the pod fails to run the operator commands due to permission issue.

# operator-sdk run bundle  quay.io/sec-eng-special/tang-operator-bundle:v0.0.25
INFO[0017] Successfully created registry pod: quay-io-sec-eng-special-tang-operator-bundle-v0-0-25 
INFO[0017] Created CatalogSource: tang-operator-catalog 
INFO[0017] OperatorGroup "operator-sdk-og" created      
INFO[0017] Created Subscription: tang-operator-v0-0-25-sub 
FATA[0120] Failed to run bundle: install plan is not available for the subscription tang-operator-v0-0-25-sub: timed out waiting for the condition 

#oc logs quay-io-sec-eng-special-tang-operator-bundle-v0-0-25  
mkdir: can't create directory '/database': Permission denied

**Comment by sarroutbi** [comment]
Image quay.io/sec-eng-special/tang-operator-bundle:v0.0.25 is used for amd64 architecture.

Multihost image is:
quay.io/sec-eng-special/tang-operator-bundle:multi-arch

Please, try that bundle, and, in case it also fails, open a new issue.

Thanks
