### ISSUE TITLE
[QUESTION]: Is anybody against archival of this repository?

### ISSUE THREAD

**Issue by sarroutbi** [latchset/tang-operator#346]
Hello. tang-operator repository in latchset organization has been forked to OpenShift organization:

https://github.com/openshift/nbde-tang-server

I would like to check if anybody subscribed to this repository is against https://github.com/latchset/tang-operator archival

**Comment by simo5** [comment]
Why fork and archive, instead of a clean transfer that would retain all the history ?

**Comment by sarroutbi** [comment]
> Why fork and archive, instead of a clean transfer that would retain all the history ?

That is a good question. They decided to fork in OpenShift organization, but I can not clarify why, sorry for that. Once forked, it seems all the history (talking from Git perspective) is kept, right?

**Comment by simo5** [comment]
I was referring to issues and PRs, but if that is a done deal I am ok archiving this one.
